language: bash
sudo: required
dist: trusty
services:
- docker
script:
# prepare qemu
- set -e
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.9.1/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# build image
- docker build -f Dockerfile-arm32v6-alpine -t kremerol/arm32v6-traefik:build .
- docker build -f Dockerfile-arm32v7-ubuntu -t kremerol/arm32v7-traefik:build .
# test image
# - docker run kremerol/arm32v7-traefik:build version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep download Dockerfile-arm32v6-alpine | sed 's,.*/download/,,' | sed 's,/.*$,,')
    echo "TAG parse from Docker file is ${TAG}"
    docker rmi kremerol/arm32v6-traefik:${TAG}
    docker tag kremerol/arm32v6-traefik:build kremerol/arm32v6-traefik:${TAG}
    docker push kremerol/arm32v6-traefik-${TAG}
    docker tag kremerol/arm32v6-traefik:build kremerol/arm32v6-traefik:latest
    docker push kremerol/arm32v6-traefik:latest

    TAG=$(grep download Dockerfile-arm32v7-ubuntu | sed 's,.*/download/,,' | sed 's,/.*$,,')
    echo "TAG parse from Docker file is ${TAG}"
    docker rmi kremerol/arm32v7-traefik:${TAG}
    docker tag kremerol/arm32v7-traefik:build kremerol/arm32v7-traefik:${TAG}
    docker push kremerol/arm32v7-traefik-${TAG}
    docker tag kremerol/arm32v7-traefik:build kremerol/arm32v7-traefik:latest
    docker push kremerol/arm32v7-traefik:latest
  fi
