FROM arm32v6/alpine
COPY tmp/qemu-arm-static /usr/bin/qemu-arm-static

ADD https://github.com/containous/traefik/releases/download/v1.3.1/traefik_linux-arm /traefik

RUN apk upgrade --no-cache &&\
    apk add --no-cache ca-certificates &&\
    chmod +x /traefik

EXPOSE 80 8080 443
ENTRYPOINT ["/traefik"]
